// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var $$Map    = require("bs-platform/lib/js/map.js");
var $$Set    = require("bs-platform/lib/js/set.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var compare = Caml_obj.caml_compare;

var PairSet = $$Set.Make(/* module */[/* compare */compare]);

var compare$1 = Caml_obj.caml_compare;

var IntMap = $$Map.Make(/* module */[/* compare */compare$1]);

exports.PairSet = PairSet;
exports.IntMap  = IntMap;
/* PairSet Not a pure module */
