// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var Curry        = require("bs-platform/lib/js/curry.js");
var Utils        = require("../utils.js");
var Coord2d      = require("../Coords/coord2d.js");
var SimpleBoard  = require("../Types/simpleBoard.js");
var TriangleTile = require("./Tiles/triangleTile.js");

var include = SimpleBoard.FromTile([
      /* Coord2d */[
        Coord2d.offset,
        Coord2d.compare
      ],
      TriangleTile.adjacents,
      TriangleTile.adjacent_coord,
      TriangleTile.direction_to_border,
      TriangleTile.to_shape
    ]);

function coordinates(size) {
  var v = /* [] */0;
  for(var y = 0 ,y_finish = size - 1 | 0; y <= y_finish; ++y){
    for(var x = 0 ,x_finish = (y << 1); x <= x_finish; ++x){
      v = /* :: */[
        /* tuple */[
          x,
          y
        ],
        v
      ];
    }
  }
  return v;
}

function auto_size(param, hint_num) {
  var cwidth = param[0];
  var size = cwidth / hint_num;
  return /* tuple */[
          hint_num,
          size,
          /* tuple */[
            cwidth,
            cwidth * Math.sqrt(3.0) / 2.0
          ]
        ];
}

var hsq3 = Math.sqrt(3.0) / 2.0;

function fi(prim) {
  return prim;
}

function offset(shape, scale, param) {
  var match_000 = param[0];
  var match_001 = param[1];
  var fy = match_001;
  return /* tuple */[
          Curry._2(Utils.Float[/* * */3], Curry._2(Utils.Float[/* / */2], Curry._2(Utils.Float[/* + */0], Curry._2(Utils.Float[/* - */1], match_000, fy), shape), 2.0), scale),
          Curry._2(Utils.Float[/* * */3], Curry._2(Utils.Float[/* * */3], Curry._2(Utils.Float[/* + */0], fy, 0.5), hsq3), scale)
        ];
}

function from_point(shape, scale, param) {
  var fshape = shape;
  var fy = Curry._2(Utils.Float[/* - */1], Curry._2(Utils.Float[/* / */2], Curry._2(Utils.Float[/* / */2], param[1], hsq3), scale), 0.5);
  var fx = Curry._2(Utils.Float[/* + */0], Curry._2(Utils.Float[/* - */1], Curry._2(Utils.Float[/* / */2], Curry._2(Utils.Float[/* * */3], param[0], 2.0), scale), fshape), fy);
  return /* tuple */[
          fx | 0,
          fy | 0
        ];
}

var Coord = include[0];

var adjacents = include[1];

var adjacent_coord = include[2];

var direction_to_border = include[3];

var tile_at_coord = include[4];

exports.Coord               = Coord;
exports.adjacents           = adjacents;
exports.adjacent_coord      = adjacent_coord;
exports.direction_to_border = direction_to_border;
exports.tile_at_coord       = tile_at_coord;
exports.coordinates         = coordinates;
exports.auto_size           = auto_size;
exports.hsq3                = hsq3;
exports.fi                  = fi;
exports.offset              = offset;
exports.from_point          = from_point;
/* include Not a pure module */
