// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var Show       = require("./show.js");
var Curry      = require("bs-platform/lib/js/curry.js");
var Paint      = require("./paint.js");
var Canvas     = require("./FFI/canvas.js");
var Circle     = require("./Boards/circle.js");
var Coord2d    = require("./Coords/coord2d.js");
var Random2    = require("./Algorithms/random2.js");
var RandomMaze = require("./randomMaze.js");

function main() {
  var options = /* record */[
    /* canvas_size : tuple */[
      1000.0,
      1000.0
    ],
    /* min_margin */50.0,
    /* size_hint */20,
    /* draw_edges : None */0,
    /* draw_walls : Some */[/* tuple */[
        1.0,
        "#ccc"
      ]],
    /* draw_shapes : None */0
  ];
  Paint.F([
          /* Coord2d */[
            Coord2d.offset,
            Coord2d.compare
          ],
          Circle.adjacents,
          Circle.adjacent_coord,
          Circle.direction_to_border,
          Circle.coordinates,
          Circle.auto_size,
          Circle.offset,
          Circle.tile_at_coord,
          Circle.from_point
        ])([
        Random2.edges,
        Random2.visited,
        Random2.max_age,
        Random2.run,
        Random2.init,
        Random2.step,
        Random2.loop_to_end,
        Random2.finished
      ]);
  var Show$prime = Show.F([
          /* Coord2d */[
            Coord2d.offset,
            Coord2d.compare
          ],
          Circle.adjacents,
          Circle.adjacent_coord,
          Circle.direction_to_border,
          Circle.coordinates,
          Circle.auto_size,
          Circle.offset,
          Circle.tile_at_coord,
          Circle.from_point
        ])([
        Random2.edges,
        Random2.visited,
        Random2.max_age,
        Random2.run,
        Random2.init,
        Random2.step,
        Random2.loop_to_end,
        Random2.finished
      ]);
  var match = Curry._1(Show$prime[/* init */7], options);
  return Curry._3(Show$prime[/* loop */8], options, match[1], match[2]);
}

var canvas = Curry._2(Canvas.createOnBody, 1000, 1000);

var ctx = canvas.getContext("2d");

RandomMaze.run(ctx, /* tuple */[
      1000.0,
      1000.0
    ]);

exports.main   = main;
exports.canvas = canvas;
exports.ctx    = ctx;
/* canvas Not a pure module */
