// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

var Show           = require("./show.js");
var Curry          = require("bs-platform/lib/js/curry.js");
var Paint          = require("./paint.js");
var Circle         = require("./Boards/circle.js");
var HexBox         = require("./Boards/hexBox.js");
var HexHex         = require("./Boards/hexHex.js");
var Random         = require("bs-platform/lib/js/random.js");
var Coord2d        = require("./Coords/coord2d.js");
var NewRect        = require("./Boards/newRect.js");
var Random2        = require("./Algorithms/random2.js");
var NewDepth       = require("./Algorithms/newDepth.js");
var Presenter      = require("./presenter.js");
var Caml_array     = require("bs-platform/lib/js/caml_array.js");
var TriangleBoard  = require("./Boards/triangleBoard.js");
var NewHexTriangle = require("./Boards/newHexTriangle.js");

function random_line() {
  return /* tuple */[
          1.0 + Random.$$int(10),
          Presenter.hsl(0, 0, Random.$$int(80))
        ];
}

function random_options(canvas_size) {
  var match = Random.bool(/* () */0);
  var match$1 = Random.bool(/* () */0);
  var match$2 = Random.bool(/* () */0);
  var $js;
  if (match$2 !== 0) {
    var hue = Random.$$int(360);
    var saturation = 70 + Random.$$int(30) | 0;
    $js = /* Some */[function (param) {
        return Presenter.hsl(hue, saturation, param);
      }];
  } else {
    $js = /* None */0;
  }
  var options_002 = /* size_hint */6 + Random.$$int(10) | 0;
  var options_003 = /* draw_edges */match !== 0 ? /* Some */[random_line(/* () */0)] : /* None */0;
  var options_004 = /* draw_walls */match$1 !== 0 ? /* Some */[random_line(/* () */0)] : /* None */0;
  var options = /* record */[
    /* canvas_size */canvas_size,
    /* min_margin */50.0,
    options_002,
    options_003,
    options_004,
    /* draw_shapes */$js
  ];
  var match$3 = +(options_003 === /* None */0 && /* draw_shapes */$js === /* None */0 && options_004 === /* None */0);
  if (match$3 !== 0) {
    var newrecord = options.slice();
    newrecord[/* draw_walls */4] = /* Some */[random_line(/* () */0)];
    return newrecord;
  } else {
    return options;
  }
}

function run(ctx, canvas_size) {
  var seed = (parseInt(Math.random() * Number.MAX_SAFE_INTEGER));
  Random.init(seed);
  console.log(/* tuple */[
        "Seed",
        seed
      ]);
  var options = random_options(canvas_size);
  var choose = function (arr) {
    return Caml_array.caml_array_get(arr, Random.$$int(arr.length));
  };
  var random_board = function () {
    return choose(/* array */[
                [
                  /* Coord2d */[
                    Coord2d.offset,
                    Coord2d.compare
                  ],
                  Circle.adjacents,
                  Circle.adjacent_coord,
                  Circle.direction_to_border,
                  Circle.coordinates,
                  Circle.auto_size,
                  Circle.offset,
                  Circle.tile_at_coord,
                  Circle.from_point
                ],
                [
                  HexBox.Coord,
                  HexBox.adjacents,
                  HexBox.adjacent_coord,
                  HexBox.direction_to_border,
                  HexBox.coordinates,
                  HexBox.auto_size,
                  HexBox.offset,
                  HexBox.tile_at_coord,
                  HexBox.from_point
                ],
                [
                  HexHex.Coord,
                  HexHex.adjacents,
                  HexHex.adjacent_coord,
                  HexHex.direction_to_border,
                  HexHex.coordinates,
                  HexHex.auto_size,
                  HexHex.offset,
                  HexHex.tile_at_coord,
                  HexHex.from_point
                ],
                [
                  TriangleBoard.Coord,
                  TriangleBoard.adjacents,
                  TriangleBoard.adjacent_coord,
                  TriangleBoard.direction_to_border,
                  TriangleBoard.coordinates,
                  TriangleBoard.auto_size,
                  TriangleBoard.offset,
                  TriangleBoard.tile_at_coord,
                  TriangleBoard.from_point
                ],
                [
                  NewHexTriangle.Coord,
                  NewHexTriangle.adjacents,
                  NewHexTriangle.adjacent_coord,
                  NewHexTriangle.direction_to_border,
                  NewHexTriangle.coordinates,
                  NewHexTriangle.auto_size,
                  NewHexTriangle.offset,
                  NewHexTriangle.tile_at_coord,
                  NewHexTriangle.from_point
                ],
                [
                  NewRect.Coord,
                  NewRect.adjacents,
                  NewRect.adjacent_coord,
                  NewRect.direction_to_border,
                  NewRect.coordinates,
                  NewRect.auto_size,
                  NewRect.offset,
                  NewRect.tile_at_coord,
                  NewRect.from_point
                ]
              ]);
  };
  var random_alg = function () {
    var $$let = NewDepth.F(NewDepth.RandomConfig(/* module */[]));
    return choose(/* array */[
                [
                  $$let[1],
                  $$let[2],
                  $$let[3],
                  $$let[12],
                  $$let[0],
                  $$let[9],
                  $$let[11],
                  $$let[4]
                ],
                [
                  Random2.edges,
                  Random2.visited,
                  Random2.max_age,
                  Random2.run,
                  Random2.init,
                  Random2.step,
                  Random2.loop_to_end,
                  Random2.finished
                ]
              ]);
  };
  var Board = random_board(/* () */0);
  var Gen = random_alg(/* () */0);
  Paint.F(Board)(Gen);
  var Show$prime = Show.F(Board)(Gen);
  var state = Curry._1(Show$prime[/* init_state */6], options);
  Curry._3(Show$prime[/* loop */8], options, ctx, state);
  ctx.font = "32px monospace";
  ctx.fillStyle = "black";
  ctx.fillText((seed.toString(16)), 5.0, 30.0);
  return /* () */0;
}

exports.random_line    = random_line;
exports.random_options = random_options;
exports.run            = run;
/* Show Not a pure module */
